plugins {
	id 'java'
	id 'org.springframework.boot' version '3.5.7'
	id 'io.spring.dependency-management' version '1.1.7'
	id "jacoco" // fuer Test-Coverage
	id "org.sonarqube" version "7.0.1.6134"
	id "org.ysb33r.doxygen" version "2.1.1"
}

group = 'de.hs-rm.de'
version = '0.0.1-SNAPSHOT'
description = 'Milefiz Softwaretechnik-Projekt 2025/26 Gruppe 3'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'com.fasterxml.jackson.core:jackson-databind'
	developmentOnly 'org.springframework.boot:spring-boot-devtools'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	implementation 'org.springframework.boot:spring-boot-starter-websocket'
	// Security for authentication/authorization and messaging support
	implementation 'org.springframework.security:spring-security-messaging'
	implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.8.14'
	
	// MapStruct for DTO mapping
	implementation 'org.mapstruct:mapstruct:1.6.3'
	annotationProcessor 'org.mapstruct:mapstruct-processor:1.6.3'
	testAnnotationProcessor 'org.mapstruct:mapstruct-processor:1.6.3'
  testImplementation 'org.awaitility:awaitility:4.2.0'
}

tasks.named('test') {
	useJUnitPlatform()
	finalizedBy jacocoTestReport
}

jacocoTestReport {
    reports {
        xml.required = true
        html.required = true
    }
}

sonar {
	properties {
		property "sonar.token", "sqa_e6aa5c7c2ead31899b13054d90dfd55fd71f3f49"
		property "sonar.host.url", "http://localhost:9000/sonar"
		property "sonar.coverage.jacoco.xmlReportPaths", "build/reports/jacoco/test/jacocoTestReport.xml"
	} 
}

doxygen {
  executables {
    doxygen {
      // TODO: Pfad zu doxygen-Programmdatei anpassen
      executableBySearchPath('doxygen')
    }
    dot {
      executableBySearchPath('dot')
    }
  }
  sourceSets {
    // Generieren mit ./gradlew doxygenDox
    main {
      sources new File(projectDir,"src/main/java")
      include '**/*.java'
      outputDir = new File(buildDir,'docs/doxygen')

      // https://doxygen.nl/manual/config.html
      options optimize_output_java: true,
        javadoc_autobrief: true,
        generate_treeview: true,
        class_graph: true,
        collaboration_graph: true,
        uml_look: true,
        have_dot: true, // nur 'true' setzen falls 'dot'-Programm verfügbar (Linux)
        recursive: true,
        extract_all: true,
        quiet: true,
        warnings: false,
        warn_if_doc_error: false,
        warn_no_paramdoc: false,
        warn_logfile: false,
        warn_if_undocumented: false,
        generate_latex: false
    }
  }
}

task build_frontend(type: Exec) {
  workingDir "${projectDir}/frontend"
  commandLine "/bin/bash", "-c", "npm clean-install && npm audit fix && npm run build && rm -rf ../src/main/resources/public && cp -rv dist ../src/main/resources/public"
}

bootJar.dependsOn build_frontend
