package de.hs_rm.de.milefiz.messaging.events;

public enum EventType {
    MOVE, JUMP, ROLL_DICE, MOVE_ERROR, ROLL_DICE_ERROR, ROLL_DICE_ERROR_MOVES_LEFT, COOLDOWN_READY, LOBBY_UPDATE, SAVE_ENERGY, SAVE_ENERGY_ERROR,
    GAME_START
}
