spring.application.name=milefiz

dice.cooldown.seconds=3

minigame.dicegame.timeout=5

minigame.slotMachineGame.timeout=5

board.planting.density = 0.8

testing.locally=false

minigame.balloongame.timeout=10

minigame.mathgame.timeout=5
minigame.mathgame.schwerwahrs=0.1

minigame.rock.paper.scissors.timeout=5

minigame.quiz.timeout=10

minigame.colorbrain.timeout=3

minigame.monkeytypegame.timeout=10